### PR TITLE
Add CF Helper, DepsGUID DB and 2 func in ModVars

### PR DESCRIPTION
**Pull request by novus213**

### CODE REVIEW

**Comment by novus213** [comment]
Add CF Helper, DepsGUID DB 2 func in Table and 2 func in ModVars
Used in [https://github.com/novus213/BG3_RacialASI/tree/Enrichissement_V5-1/RacialASI](https://github.com/novus213/BG3_RacialASI/tree/Enrichissement_V5-1/RacialASI)
In waiting pull request accept, i have create a surcharge Mod [https://github.com/novus213/BG3_KendersLabsCoreLibs](https://github.com/novus213/BG3_KendersLabsCoreLibs)

**Comment by AtilioA** [comment]
Hey, feel free to copy over this repo to your own lib. However, checking dependencies within a dependency can be tricky for obvious reasons :sweat_smile:. The best you can do is add checks on the main mod and add the dependencies in the meta.lsx file.

**Comment by novus213** [comment]
Hey, So i keep my Surcharge Mod of VC mod ?

**Comment by AtilioA** [comment]
Just copy over into your own thing

**Comment by novus213** [comment]
Merge Pull closed :
VC Surcharge on https://github.com/novus213/BG3_KendersLabsCoreLibs

**Pull request closed without merging**
